apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdxl-deployment
  labels:
    app: sdxl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sdxl
  template:
    metadata:
      labels:
        app: sdxl
    spec:
      containers:
      - name: sdxl
        image: openrhino/stable-diffusion:sdxl-initialized-webui-latest
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU

---

kind: Service
apiVersion: v1
metadata:
  name: sdxl
spec:
  selector:
    app: sdxl
  ports:
    - port: 7860 # Default port for the image
  type: NodePort
