# permissions for end users to view grapejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grapejob-viewer-role
rules:
- apiGroups:
  - graph.limingyu.io
  resources:
  - grapejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.limingyu.io
  resources:
  - grapejobs/status
  verbs:
  - get
