kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoClusterRole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoClusterRoleBinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-cndev
roleRef:
  kind: ClusterRole
  name: demoClusterRole
  apiGroup: rbac.authorization.k8s.io
