kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoRole2
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoRoleBinding2
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: demoRole2
  apiGroup: rbac.authorization.k8s.io

