kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoRole
  namespace: demo-cndev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoRoleBinding
  namespace: demo-cndev
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: demoRole
  apiGroup: rbac.authorization.k8s.io
