apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  selector:
    matchLabels:
      app: spring-demo
      tier: front-end
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-demo
        tier: front-end
    spec:
      containers:
      - name: springmsdemo
        image: limingyu007/springmsdemo:2.0
