apiVersion: v1
kind: Service
metadata:
  name: sts-demo-busybox
spec:
  selector:
    app: sts-demo-busybox
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-demo-busybox
spec:
  selector:
    matchLabels:
      app: sts-demo-busybox
  serviceName: sts-demo-busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: sts-demo-busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.28.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        command:
          - sleep
          - "100000"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi


