# permissions for end users to edit grapejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grapejob-editor-role
rules:
- apiGroups:
  - graph.limingyu.io
  resources:
  - grapejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - graph.limingyu.io
  resources:
  - grapejobs/status
  verbs:
  - get
