apiVersion: v1
kind: Service
metadata:
  name: grape-mpi-controller
spec:
  selector:
    app: grape-mpi
    type: controller
  ports:
  - port: 20000
    targetPort: 20000

---

apiVersion: batch/v1
kind: Job
metadata:
  name: grape-mpi-controller
spec:
  ttlSecondsAfterFinished: 1000
  template:
    metadata:
      labels:
        app: grape-mpi
        type: controller
    spec:
      containers:
      - name: grape-mpi-controller
        image: limingyu007/run_app:v0.2
        command: ["mpirun"]
        args: ["-launcher", "manual", "-verbose", 
          "-disable-hostname-propagation", "-hosts", "0,1", 
          "/libgrape-lite-src/build/run_app",  
          "--vfile", "/libgrape-lite-src/dataset/p2p-31.v", 
          "--efile", "/libgrape-lite-src/dataset/p2p-31.e", 
          "--application", "bfs", "--out_prefix", "stdout"]
        env:
        - name: MPICH_PORT_RANGE
          value: "20000:20100"
        lifecycle:
          postStart:
            exec:
              command: ["bash","-c", "for i in {0..1}; 
  do amqp-publish --url=amqp://guest:guest@rabbitmq-service:5672 -r mpiworker -b ${i}; done"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 20000
      restartPolicy: Never

