apiVersion: batch/v1
kind: Job
metadata:
  name: grape-mpi-workers
spec:
  ttlSecondsAfterFinished: 1000
  parallelism: 4
  template:
    metadata:
      labels:
        app: grape-mpi
        type: workers
    spec:
      containers:
      - name: grape-mpi
        image: limingyu007/run_app:v0.2
        command: 
        - bash
        - "-c"
        - |
          id=$(amqp-consume --url amqp://guest:guest@rabbitmq-service:5672 -q mpiworker -c 1 cat)
          /usr/bin/hydra_pmi_proxy --control-port grape-mpi-controller:20000 --debug \
          --rmk user --launcher manual --demux poll --pgid 0 \
          --retries 10 --usize -2 --proxy-id $id       
        resources: 
          requests:
            memory: "32Mi"
            cpu: "0.1"     
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never